# Generated by Django 3.0.1 on 2019-12-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('enterprise', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cpu',
                'verbose_name_plural': 'Cpus',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('supported_cpu', models.CharField(max_length=20)),
                ('ram_slots', models.IntegerField()),
                ('supported_ram_size', models.IntegerField()),
                ('integrated_video', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Motherboard',
                'verbose_name_plural': 'Motherboards',
            },
        ),
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_size', models.IntegerField()),
                ('name', models.CharField(default='Hiper X', max_length=7)),
            ],
            options={
                'verbose_name': 'RamMemory',
                'verbose_name_plural': 'RamMemorys',
            },
        ),
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'VideoCard',
                'verbose_name_plural': 'VideoCards',
            },
        ),
    ]
