# Generated by Django 3.0.1 on 2019-12-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='supported_cpu',
            field=models.CharField(max_length=100),
        ),
    ]
