# Generated by Django 3.0.1 on 2019-12-20 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191219_1918'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='motherboard',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rammemory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videocard',
            options={},
        ),
    ]
