# Generated by Django 3.0.1 on 2019-12-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191219_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motherboard',
            name='integrated_video',
            field=models.BooleanField(default=True),
        ),
    ]
