# Generated by Django 3.0.1 on 2019-12-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='restrictions',
            field=models.BooleanField(),
        ),
    ]
