# Generated by Django 3.0.1 on 2019-12-18 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191218_1748'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Cpu',
        ),
    ]
