# Generated by Django 3.0.1 on 2019-12-18 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191218_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpu',
            old_name='model',
            new_name='enterprise',
        ),
        migrations.RenameField(
            model_name='cpu',
            old_name='piece',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='cpu',
            name='restrictions',
        ),
    ]
