# Generated by Django 3.0.1 on 2019-12-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20191218_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpu',
            name='name',
            field=models.CharField(auto_created=True, default='Intel', max_length=60),
        ),
    ]
