# Generated by Django 3.0.1 on 2019-12-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20191218_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('supported_cpu', models.CharField(max_length=5)),
                ('ram_slots', models.IntegerField()),
                ('supported_ram_size', models.IntegerField()),
                ('integrated_video', models.BooleanField()),
            ],
        ),
    ]
