# Generated by Django 3.0.1 on 2019-12-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_motherboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='RamMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram_size', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='supported_cpu',
            field=models.CharField(max_length=20),
        ),
    ]
