# Generated by Django 3.0.1 on 2019-12-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20191218_2004'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
