# Generated by Django 3.0.1 on 2019-12-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_videocard'),
    ]

    operations = [
        migrations.AddField(
            model_name='rammemory',
            name='name',
            field=models.CharField(default='Hiper X', max_length=7),
        ),
    ]
