# Generated by Django 3.0.1 on 2019-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0013_rammemory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.ManyToManyField(to='products.Cpu')),
                ('motherboard', models.ManyToManyField(to='products.Motherboard')),
                ('ramMemory', models.ManyToManyField(to='products.RamMemory')),
                ('videoCard', models.ManyToManyField(to='products.VideoCard')),
            ],
        ),
    ]
