# Generated by Django 3.0.1 on 2019-12-19 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Default', max_length=150),
            preserve_default=False,
        ),
    ]
