# Generated by Django 3.0.1 on 2019-12-19 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20191219_1918'),
        ('orders', '0002_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.AddField(
            model_name='order',
            name='motherboard',
            field=models.ManyToManyField(to='products.Motherboard'),
        ),
        migrations.AddField(
            model_name='order',
            name='rammemory',
            field=models.ManyToManyField(to='products.RamMemory'),
        ),
        migrations.AddField(
            model_name='order',
            name='videoCard',
            field=models.ManyToManyField(to='products.VideoCard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
