# Generated by Django 3.0.1 on 2019-12-19 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191219_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='id',
            new_name='Id',
        ),
    ]
