# Generated by Django 3.0.1 on 2019-12-19 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20191219_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='videoCard',
            new_name='videocard',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Id',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default='zero', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
