# Generated by Django 3.0.1 on 2019-12-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20191219_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.CharField(default='Default', max_length=120),
            preserve_default=False,
        ),
    ]
