# Generated by Django 3.0.1 on 2019-12-22 17:09

from django.db import migrations, models
import orders.validators


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191222_1409'),
        ('orders', '0007_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpu',
            field=models.ManyToManyField(to='products.Cpu', validators=[orders.validators.validate_cpu]),
        ),
    ]
