# Generated by Django 3.0.1 on 2019-12-22 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20191222_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='order',
            name='motherboard',
        ),
    ]
