# Generated by Django 3.0.1 on 2019-12-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191222_1409'),
        ('orders', '0010_auto_20191222_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cpu',
            field=models.ManyToManyField(to='products.Cpu'),
        ),
        migrations.AddField(
            model_name='order',
            name='motherboard',
            field=models.ManyToManyField(to='products.Motherboard'),
        ),
    ]
