# Generated by Django 3.0.1 on 2019-12-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20191226_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='rammemory2',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
