# Generated by Django 3.0.1 on 2019-12-27 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20191226_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cpu',
            field=models.CharField(default=None, max_length=200, verbose_name='cpu'),
        ),
        migrations.AlterField(
            model_name='order',
            name='motherboard',
            field=models.CharField(default=None, max_length=200, verbose_name='motherboard'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default=None, max_length=120),
        ),
    ]
