# Generated by Django 3.0.1 on 2019-12-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20191226_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rammemory3',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rammemory4',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
